### ISSUE TITLE
FEATURE REQUEST: Allow libraries other than “Movies”

### ISSUE THREAD

**Issue by JesseWebDotCom** [se1exin/Plex-Library-Cleaner#8]
First - thanks for this.  The idea is spot on and there a lot of potential here.

After a bit of struggling to get this working, I discovered the app is hard coded to expect a single library called “movies”.  My temporary workaround was to use docker to map the app/plex folder to a local directory where I downloaded and modified classes.py.

Any chance to allow the user to use their own library names?  And ideally support more than 1 library?

**Comment by se1exin** [comment]
Hi @JesseWebDotCom thanks for taking the time to submit this feature request. Yes you are right that it is currently hardcoded to use "Movies", which was just my setup at the time that I created this. You are now the second to mention the use of different library names (the first being in #7, so I'll see if I can make this higher priority.

If I roll a PR with a different docker image are you be happy to test it out for me?

**Comment by JesseWebDotCom** [comment]
Happy to test - just let me know.  Thanks.  I also haven’t gotten the app to actually delete files but I’ll log that issue if it persists in the next test version.

**Comment by se1exin** [comment]
Thanks @JesseWebDotCom.

Please test the docker image `selexin/plex-library-cleaner:issue-8` and use the new environment var `LIBRARY_NAMES` to pass in your library names. You can pass in multiple names by separating them with the `;` character.

For example:
```
docker run \
	-e PLEX_BASE_URL="http://192.169.1.100:32400" \
	-e PLEX_TOKEN="somerandomstring" \
	-e LIBRARY_NAMES="Movies 1;Movies 2" \
	-p 5000:80 \
	selexin/plex-library-cleaner:issue-8
```

I'm intrigued by your mention of not being able to delete files, but yes at this point it's hard to tell if it is or is not related.

**Comment by JesseWebDotCom** [comment]
- Successfully picked up my 2 libraries
- Fails if I had quotes around the names  in my docker compose (maybe you can just ignore single or double quotes)
```
    environment:
      - LIBRARY_NAMES="Adult Movies;Kid Videos"
```

### Separately:

- Suggestion: add a table header with the library name to be able to tell which files belong to which library (without having to look at the path)
- FYI - Got the delete working (maybe you can highlight in your README.md); You need to check _Settings | Library | Allow media deletion_


FWIW, here’s my docker compose if you wanted to add it to your README.md:
```
version: '3'

services:

  plex-library-cleaner-issue8:
    image: selexin/plex-library-cleaner:issue-8
    container_name: plex-library-cleaner-issue8
    hostname: plex-library-cleaner-issue8
    ports:
      - "5000:80"    
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=1234567890
      - PLEX_BASE_URL=http://192.168.1.12:32400
      - LIBRARY_NAMES=Adult Movies;Kid Videos
    restart: unless-stopped
```
